"""Pure carbon-emissions calculation (Appendix C #6).

All functions here are pure: same inputs -> same outputs, no I/O, no clock, no
randomness. Emissions combine two published sources (see ``carbon.factors``):

  * *moving* emissions — distance x payload x a gCO2e/tonne-km factor, the
    fleet-transporter trip leg through the Area of Interest (AoI);
  * *idle* emissions — CPP / parking-area dwell time x a gCO2e/idle-minute
    factor (engine / reefer-unit idling while parked).

A deterministic synthetic "fleet-of-trailers-in-AoI" book is generated by
``seed_aoi_fleet`` so the ``/rollup`` endpoint is reproducible across runs and
hosts (no unseeded randomness anywhere).
"""
from __future__ import annotations

import hashlib
from typing import Iterable

from . import factors

# Grams -> kilograms.
_G_PER_KG = 1000.0

# Rounding applied to reported kilogram figures (3 dp = grams precision).
_ROUND_KG = 3


def _kg(grams: float) -> float:
    return round(grams / _G_PER_KG, _ROUND_KG)


def trip_emissions_kg(
    distance_km: float, payload_tonnes: float, vehicle_class: str
) -> float:
    """Moving (well-to-wheel) emissions for one trip leg, in kg CO2e.

    Scales linearly with both ``distance_km`` and ``payload_tonnes`` via the
    published gCO2e/tonne-km factor for ``vehicle_class``. Negative inputs are
    clamped to zero so a malformed row can never produce a negative total.
    """
    distance_km = max(0.0, float(distance_km))
    payload_tonnes = max(0.0, float(payload_tonnes))
    grams = distance_km * payload_tonnes * factors.tonne_km_factor(vehicle_class)
    return _kg(grams)


def idle_emissions_kg(idle_minutes: float, vehicle_class: str) -> float:
    """CPP / parking-area dwell (idle) emissions, in kg CO2e.

    Scales linearly with ``idle_minutes`` via the published gCO2e/idle-minute
    factor for ``vehicle_class`` (engine, plus refrigeration unit for reefers).
    """
    idle_minutes = max(0.0, float(idle_minutes))
    grams = idle_minutes * factors.idle_minute_factor(vehicle_class)
    return _kg(grams)


def vehicle_emissions_kg(
    distance_km: float,
    payload_tonnes: float,
    idle_minutes: float,
    vehicle_class: str,
) -> float:
    """Total emissions for one vehicle = moving + idle, in kg CO2e."""
    moving = trip_emissions_kg(distance_km, payload_tonnes, vehicle_class)
    idle = idle_emissions_kg(idle_minutes, vehicle_class)
    return round(moving + idle, _ROUND_KG)


def aoi_rollup(trips: Iterable[dict]) -> dict:
    """Roll up a fleet of in-AoI trailer trips into an emissions summary.

    Each trip dict may carry ``distance_km``, ``payload_tonnes``,
    ``idle_minutes`` and ``vehicle_class`` (missing keys default to 0 / the
    default class). Returns::

        {
          "total_kg": float,
          "by_class": {<class>: kg, ...},      # only classes that appear
          "by_source": {"moving": kg, "idle": kg},
          "vehicle_count": int,
        }

    Invariant (asserted in tests): ``by_source.moving + by_source.idle`` equals
    ``total_kg`` within rounding, and ``sum(by_class.values())`` equals it too.
    """
    by_class: dict[str, float] = {}
    moving_total = 0.0
    idle_total = 0.0
    count = 0

    for trip in trips:
        count += 1
        vclass = str(trip.get("vehicle_class", factors.DEFAULT_CLASS) or factors.DEFAULT_CLASS).upper()
        moving = trip_emissions_kg(
            trip.get("distance_km", 0.0), trip.get("payload_tonnes", 0.0), vclass
        )
        idle = idle_emissions_kg(trip.get("idle_minutes", 0.0), vclass)

        moving_total += moving
        idle_total += idle
        by_class[vclass] = round(by_class.get(vclass, 0.0) + moving + idle, _ROUND_KG)

    total = round(moving_total + idle_total, _ROUND_KG)
    return {
        "total_kg": total,
        "by_class": dict(sorted(by_class.items())),
        "by_source": {
            "moving": round(moving_total, _ROUND_KG),
            "idle": round(idle_total, _ROUND_KG),
        },
        "vehicle_count": count,
    }


# --------------------------------------------------------------------------- seed
# Deterministic synthetic fleet of trailers currently in the Area of Interest.
# Stands in for the fleet-transporter telematics + CPP/parking dwell feeds
# (simulated per docs/ASSUMPTIONS.md "Carbon (C6)"). Everything below is derived
# from a fixed SEED via SHA-256, so the /rollup output is byte-identical across
# runs and hosts — no unseeded randomness.
SEED = 20260617

# Class mix (in stable order) for the synthetic AoI fleet. Roughly mirrors a
# container-port trailer population: mostly articulated HGVs, some rigids and
# reefers, a few light commercials.
_CLASS_MIX: tuple[str, ...] = (
    factors.HGV, factors.HGV, factors.HGV, factors.HGV, factors.HGV,
    factors.RIGID, factors.RIGID,
    factors.REEFER, factors.REEFER,
    factors.LGV,
)


def _det_unit(key: str) -> float:
    """Deterministic value in [0, 1) from a SHA-256 of ``key`` (no RNG)."""
    h = int.from_bytes(hashlib.sha256(key.encode()).digest()[:8], "big")
    return (h % 1_000_000) / 1_000_000.0


def seed_aoi_fleet(n: int = 200) -> list[dict]:
    """Build a deterministic fleet-of-trailers-in-AoI book of ``n`` trips.

    Each trip carries a class, an in-AoI trip distance (the corridor leg, ~5-40
    km), a payload (laden tonnes), and a CPP/parking dwell (idle minutes). All
    values are SHA-256-derived from the trip index + ``SEED`` so the resulting
    rollup is fully reproducible.
    """
    fleet: list[dict] = []
    for i in range(max(0, int(n))):
        base = f"{SEED}:{i}"
        vclass = _CLASS_MIX[i % len(_CLASS_MIX)]

        # In-AoI corridor leg: 5..40 km (NH-348 port -> Karal Phata is ~40 km).
        distance_km = round(5.0 + _det_unit(base + ":dist") * 35.0, 2)
        # Laden payload: 2..30 t for heavy freight, 0.3..2 t for light.
        if vclass == factors.LGV:
            payload_tonnes = round(0.3 + _det_unit(base + ":load") * 1.7, 2)
        else:
            payload_tonnes = round(2.0 + _det_unit(base + ":load") * 28.0, 2)
        # CPP / parking-area dwell: 0..180 min of idling.
        idle_minutes = round(_det_unit(base + ":idle") * 180.0, 1)

        fleet.append(
            {
                "trailer_id": f"AOI-{i:05d}",
                "vehicle_class": vclass,
                "distance_km": distance_km,
                "payload_tonnes": payload_tonnes,
                "idle_minutes": idle_minutes,
            }
        )
    return fleet


__all__ = [
    "trip_emissions_kg",
    "idle_emissions_kg",
    "vehicle_emissions_kg",
    "aoi_rollup",
    "seed_aoi_fleet",
    "SEED",
]
