"""/api/push — WebPush subscription + delivery for the trucking-app PWA.

The driver-facing PWA (mobile-pwa/) registers its service-worker push
subscription here so the gateway can deliver re-route notifications even when the
app is backgrounded. The channel is:

    GET  /api/push/vapid-public-key   -> the VAPID public key the SW subscribes with
    POST /api/push/subscribe          -> store {device_id, subscription}
    POST /api/push/unsubscribe        -> drop a device's subscription
    GET  /api/push/status             -> demo introspection (configured? how many subs)
    POST /api/push/test/{device_id}   -> send a test notification (demo / e2e)

Delivery is best-effort and degrades cleanly:

* VAPID keys come from ``VAPID_PUBLIC_KEY`` / ``VAPID_PRIVATE_KEY`` (generated by
  ``make vapid-keys``). With no private key configured, subscriptions are still
  accepted but no browser push is sent — the PWA then relies on its WebSocket
  ``reroute`` frame / in-app polling fallback, so the demo never hard-depends on
  a key being present.
* ``pywebpush`` is imported lazily; if the lib is missing, push silently no-ops.

Subscriptions live in an in-memory map keyed by ``device_id`` (demo-scale; the
gateway is the only push origin and a fresh stack re-pairs in seconds).
"""
from __future__ import annotations

import asyncio
import json
from typing import Any, Dict, Optional

from fastapi import APIRouter, Body, Depends, HTTPException

from .. import audit
from ..logging import get_logger
from ..metrics import REQUESTS
from ..state import GatewayState, get_state

log = get_logger("gateway.push")

router = APIRouter(prefix="/api/push", tags=["push"])

# device_id -> the browser PushSubscription dict (endpoint + keys). In-memory.
SUBSCRIPTIONS: Dict[str, dict] = {}


@router.get("/vapid-public-key")
async def vapid_public_key(state: GatewayState = Depends(get_state)) -> dict:
    """The VAPID public key the service-worker uses for ``pushManager.subscribe``.

    Returns ``{"key": null}`` when no key is configured so the PWA can detect the
    "push disabled" state and quietly fall back to WS / polling.
    """
    key = state.cfg.vapid_public_key.strip() or None
    return {"key": key, "configured": bool(key)}


@router.post("/subscribe")
async def subscribe(
    body: Dict[str, Any] = Body(...),
    state: GatewayState = Depends(get_state),
) -> dict:
    """Store a PWA's push subscription against its device_id.

    Body: ``{"device_id": "TRK-...", "subscription": {endpoint, keys}}``.
    """
    device_id = body.get("device_id")
    subscription = body.get("subscription")
    if not device_id or not isinstance(subscription, dict):
        REQUESTS.labels("push", "invalid").inc()
        raise HTTPException(status_code=422, detail={"error": "device_id_and_subscription_required"})
    SUBSCRIPTIONS[device_id] = subscription
    log.info("push_subscribed", device_id=device_id, subs=len(SUBSCRIPTIONS))
    REQUESTS.labels("push", "ok").inc()
    return {"subscribed": True, "device_id": device_id, "total": len(SUBSCRIPTIONS)}


@router.post("/unsubscribe")
async def unsubscribe(body: Dict[str, Any] = Body(...)) -> dict:
    device_id = body.get("device_id")
    existed = SUBSCRIPTIONS.pop(device_id, None) is not None
    return {"unsubscribed": existed, "device_id": device_id, "total": len(SUBSCRIPTIONS)}


@router.get("/status")
async def status(state: GatewayState = Depends(get_state)) -> dict:
    """Demo introspection: is push configured, and which devices are subscribed."""
    return {
        "configured": bool(state.cfg.vapid_public_key.strip() and state.cfg.vapid_private_key.strip()),
        "pywebpush_available": _pywebpush_available(),
        "subscriptions": len(SUBSCRIPTIONS),
        "devices": list(SUBSCRIPTIONS.keys()),
    }


@router.post("/test/{device_id}")
async def test_push(device_id: str, state: GatewayState = Depends(get_state)) -> dict:
    """Send a test notification to one device (used by the demo + Playwright)."""
    payload = {
        "type": "test",
        "title": "JNPA Trucking",
        "body": "Push channel is live.",
        "device_id": device_id,
    }
    delivered = await deliver(state, device_id, payload)
    return {"delivered": delivered, "device_id": device_id}


# --------------------------------------------------------------------- delivery
def _pywebpush_available() -> bool:
    try:
        import pywebpush  # noqa: F401
        return True
    except Exception:  # noqa: BLE001
        return False


async def deliver(state: GatewayState, device_id: str, payload: dict) -> bool:
    """Best-effort WebPush to one device. Returns True if a push was sent.

    Runs the (blocking) pywebpush call in a thread so it never stalls the event
    loop. Any failure (no sub, no key, lib missing, dead endpoint) is swallowed
    and returns False — the caller still has the WS reroute frame as a fallback.
    """
    cfg = state.cfg
    # Best-effort delivery-history row for every attempt (audit trail).
    msg = payload.get("body") or payload.get("title") or payload.get("type") or ""
    event_id = payload.get("alert_id") or payload.get("case_id") or payload.get("id")

    def _log(status: str, provider: Any) -> None:
        audit.spawn(
            audit.log_notification(
                channel="webpush", event_id=event_id, receiver=device_id,
                message=str(msg), delivery_status=status, provider_response=provider,
            )
        )

    sub = SUBSCRIPTIONS.get(device_id)
    if sub is None:
        log.debug("push_no_subscription", device_id=device_id)
        _log("NO_SUBSCRIPTION", {"reason": "no_subscription"})
        return False
    if not (cfg.vapid_private_key.strip() and cfg.vapid_public_key.strip()):
        log.debug("push_not_configured", device_id=device_id)
        _log("SKIPPED", {"reason": "vapid_not_configured"})
        return False
    try:
        ok = await asyncio.to_thread(_send_blocking, sub, payload, cfg)
        _log("SENT" if ok else "FAILED", {"pywebpush": ok})
        return ok
    except Exception as exc:  # noqa: BLE001
        log.warning("push_delivery_failed", device_id=device_id, error=str(exc))
        _log("FAILED", {"error": str(exc)})
        # A 404/410 means the endpoint is gone — drop the stale subscription.
        if "410" in str(exc) or "404" in str(exc):
            SUBSCRIPTIONS.pop(device_id, None)
        return False


def _send_blocking(sub: dict, payload: dict, cfg) -> bool:
    from pywebpush import webpush

    webpush(
        subscription_info=sub,
        data=json.dumps(payload),
        vapid_private_key=cfg.vapid_private_key.strip(),
        vapid_claims={"sub": cfg.vapid_subject},
        ttl=120,
    )
    return True


__all__ = ["router", "deliver", "SUBSCRIPTIONS"]
