#!/usr/bin/env python3
"""Generate a VAPID keypair for the trucking-app PWA WebPush channel.

`make vapid-keys` runs this. It mints an ES256 (P-256) keypair and prints the
two env vars the gateway reads (`VAPID_PUBLIC_KEY` / `VAPID_PRIVATE_KEY`):

* the PUBLIC key in the *application-server* format browsers expect — the raw
  uncompressed point, URL-safe base64 without padding (what
  ``pushManager.subscribe({applicationServerKey})`` takes), and
* the PRIVATE key as the DER PKCS#8, URL-safe base64 without padding (what
  ``pywebpush(vapid_private_key=...)`` accepts directly).

If ``.env.local`` exists and does not already define the keys, they are appended
to it so ``make up`` picks them up. Existing values are never overwritten (the
script reports them as already set). With no ``.env.local`` the keys are just
printed for the operator to paste.

The keys are demo credentials. They are NOT secrets in any real sense here (the
gateway is a PoC), but they are still generated per-environment so two stacks do
not share a VAPID identity.
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

ENV_FILE = Path(__file__).resolve().parent.parent / ".env.local"


def _b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def generate() -> tuple[str, str]:
    """Return (public_application_server_key, private_pkcs8_der) both b64url."""
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError:  # pragma: no cover
        sys.exit(
            "cryptography not installed. Run `pip install pywebpush` "
            "(or `make install-shared`) first."
        )

    private_key = ec.generate_private_key(ec.SECP256R1())
    public_key = private_key.public_key()

    # Public: raw uncompressed point (0x04 || X || Y), 65 bytes -> b64url.
    pub_raw = public_key.public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint,
    )
    # Private: PKCS#8 DER -> b64url (pywebpush accepts this form directly).
    priv_der = private_key.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    return _b64url(pub_raw), _b64url(priv_der)


def _existing_keys(text: str) -> set[str]:
    found = set()
    for line in text.splitlines():
        line = line.strip()
        for var in ("VAPID_PUBLIC_KEY", "VAPID_PRIVATE_KEY"):
            if line.startswith(f"{var}=") and line.split("=", 1)[1].strip():
                found.add(var)
    return found


def main() -> None:
    public, private = generate()

    print("# VAPID keypair for the trucking-app PWA WebPush channel")
    print(f"VAPID_PUBLIC_KEY={public}")
    print(f"VAPID_PRIVATE_KEY={private}")
    print()

    if not ENV_FILE.exists():
        print(f"(no {ENV_FILE.name} found — paste the two lines above into your env)")
        return

    text = ENV_FILE.read_text()
    already = _existing_keys(text)
    if "VAPID_PUBLIC_KEY" in already and "VAPID_PRIVATE_KEY" in already:
        print(f"{ENV_FILE.name} already defines both keys — leaving them untouched.")
        return

    block = [
        "",
        "# --- WebPush (trucking-app PWA) — generated by `make vapid-keys` ---",
    ]
    if "VAPID_PUBLIC_KEY" not in already:
        block.append(f"VAPID_PUBLIC_KEY={public}")
    if "VAPID_PRIVATE_KEY" not in already:
        block.append(f"VAPID_PRIVATE_KEY={private}")
    with ENV_FILE.open("a") as fh:
        fh.write("\n".join(block) + "\n")
    print(f"Appended VAPID keys to {ENV_FILE.name}. Run `make up` to apply.")


if __name__ == "__main__":
    main()
